version: '3.7'

services:
  soft_teacher:
    build: .
    # loop command
    entrypoint: tail -f /dev/null
    volumes:
    - ./ws:/root/ws
    #dataset path if you pariticipate in hackerton this option has to be blocked 
    working_dir: /root/ws
    privileged: true
    network_mode: host
    ipc: host
    #GPU
    deploy:
      resources:
        reservations:
          devices: 
            - capabilities: [gpu]